# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y libtidy5deb1 libzmq3-dev
          pip3 install nose==1.3.7 selenium==3.141.0 coverage pyvirtualdisplay pytest

      - name: Start services
        run: |
          sudo systemctl start mongod
          sudo systemctl start docker

      - name: Install INGInious
        run: pip3 install .
        
      - name: Mitigate MarkupSafe 2.1+ issues
        run: pip3 install --upgrade markupsafe==2.0.1

      - name: Launch nose tests
        run: nosetests -v --with-coverage --cover-package=inginious --cover-branches --cover-html -I "^test_"

      - name: Launch pytest tests
        run: coverage run --branch -m pytest -v

      - name: Generate coverage report
        if: always()
        run: |
          coverage report --include="inginious/*"
          coverage xml --include="inginious/*"

      - name: Save coverage output
        uses: codacy/codacy-coverage-reporter-action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
